server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: springauth

springdoc:
  swagger-ui:
    path: /docs
    urls:
      - name: springauth API
        url: /springdoc/springauth.json

jwt:
  secret: zLk0J8ABMzIbiNLKf4N6OKiOE6rmM7Evzq6U7WwnCMc=
  expiration: 3600000 # 밀리초 기준 (1시간)